# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(186, 230)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.height = QtWidgets.QSpinBox(Dialog)
        self.height.setMinimum(64)
        self.height.setMaximum(1024)
        self.height.setSingleStep(0)
        self.height.setProperty("value", 128)
        self.height.setObjectName("height")
        self.gridLayout.addWidget(self.height, 4, 1, 1, 1)
        self.base_name = QtWidgets.QLineEdit(Dialog)
        self.base_name.setObjectName("base_name")
        self.gridLayout.addWidget(self.base_name, 0, 0, 1, 2)
        self.Cancel = QtWidgets.QPushButton(Dialog)
        self.Cancel.setObjectName("Cancel")
        self.gridLayout.addWidget(self.Cancel, 5, 0, 1, 1)
        self.width = QtWidgets.QSpinBox(Dialog)
        self.width.setMinimum(64)
        self.width.setMaximum(1024)
        self.width.setProperty("value", 128)
        self.width.setObjectName("width")
        self.gridLayout.addWidget(self.width, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.screenshot = QtWidgets.QPushButton(Dialog)
        self.screenshot.setObjectName("screenshot")
        self.gridLayout.addWidget(self.screenshot, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.top = QtWidgets.QCheckBox(self.groupBox)
        self.top.setChecked(True)
        self.top.setObjectName("top")
        self.gridLayout_2.addWidget(self.top, 0, 0, 1, 1)
        self.persp = QtWidgets.QCheckBox(self.groupBox)
        self.persp.setChecked(True)
        self.persp.setObjectName("persp")
        self.gridLayout_2.addWidget(self.persp, 0, 1, 1, 1)
        self.side = QtWidgets.QCheckBox(self.groupBox)
        self.side.setChecked(True)
        self.side.setObjectName("side")
        self.gridLayout_2.addWidget(self.side, 1, 0, 1, 1)
        self.front = QtWidgets.QCheckBox(self.groupBox)
        self.front.setChecked(True)
        self.front.setObjectName("front")
        self.gridLayout_2.addWidget(self.front, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 2)
        self.frame_all = QtWidgets.QCheckBox(Dialog)
        self.frame_all.setChecked(True)
        self.frame_all.setObjectName("frame_all")
        self.gridLayout.addWidget(self.frame_all, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.base_name.setText(_translate("Dialog", "Model_name"))
        self.Cancel.setText(_translate("Dialog", "Cancel"))
        self.label_2.setText(_translate("Dialog", "Height"))
        self.screenshot.setText(_translate("Dialog", "Screen Shot"))
        self.label.setText(_translate("Dialog", "Width"))
        self.groupBox.setTitle(_translate("Dialog", "Views"))
        self.top.setText(_translate("Dialog", "Top"))
        self.persp.setText(_translate("Dialog", "Persp"))
        self.side.setText(_translate("Dialog", "Side"))
        self.front.setText(_translate("Dialog", "Front"))
        self.frame_all.setText(_translate("Dialog", "Frame All"))
